"""Add default for first_image

Revision ID: 4797191d54a5
Revises: 9c80c83b5711
Create Date: 2021-09-16 15:13:01.674558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4797191d54a5'
down_revision = '9c80c83b5711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
