version: "3.3"

services:
  docker_caller:
    container_name: Pipeline-Caller
    build: ./caller
    volumes:
      # Code
      - ./caller:/app
      # Docker engine
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - '8080:8080'
    env_file:
    - .env
    
